### ISSUE TITLE
Issues with some links on Course2017.md

### ISSUE THREAD

**Issue by emilhem** [DSLsofMath/DSLsofMath#16]
There are broken links on the [Course2017.md](/DSLsofMath/DSLsofMath/blob/master/Course2017.md#lectures)

In the part
```MarkDown
*Note*: the summaries are written as a mixture of markdown and lhs.
To compile them, you can use a suitably modified form of this
[Makefile](comp/Makefile) and the [bib](comp/ref.bib) and
[template.tex](comp/template.tex) files.
```
the links to the Makefile, bib, and template.tex are broken which makes generating the Haskell/LaTeX code to PDF difficult.

**Comment by patrikja** [comment]
Thanks - the broken links are now fixed by 0d0b9fc4f847c676af625b48faf47e70bdef2122
