### ISSUE TITLE
Provide easy way of compiling lecture notes

### ISSUE THREAD

**Issue by dschoepe** [DSLsofMath/DSLsofMath#21]
There should be an easy way, possibly using `make`, to produce PDFs from the literate Haskell files, which also contain LaTeX code that makes is somewhat hard to read them in the raw form.

There is a Makefile in the L/ directory, but it cannot compile any other lecture notes.

**Comment by patrikja** [comment]
For me "make" works in the L/ directory and it produces a PDF. 
I make a snapshot of that PDF and check it into the L/snapshots/ directory at least once a week.
Pleas re-open this issue if problems remain.
/Patrik

**Comment by dschoepe** [comment]
This only produces a PDF with notes about the first lecture for me.

What I meant is that the individual lectures in the sub-folders in L, such as L/02, cannot be compiled in their current form. However, they are also not optimally readable in lhs form since they contain a fair amount of latex formatting in them.

**Comment by dschoepe** [comment]
Nevermind, I noticed that this file is being extended to include the other lecture notes.
