### ISSUE TITLE
Lecture04.lhs does not convert to pdf, but all other lecture notes do.

### ISSUE THREAD

**Issue by MaximilianAlgehed** [DSLsofMath/DSLsofMath#3]
Hi all,

I am having difficulties converting Lecture04.lhs to pdf using the makefile. I get the following error:

`
pandoc -s --template ../aux/template.tex --bibliography=../aux/ref.bib -f markdown+lhs Lecture04.lhs -t latex -o Lecture04.tex && latexmk -pdf Lecture04.tex
pandoc-citeproc: Error in $[2][6]: When expecting a product of 3 values, encountered an Array of 2 elements instead
`

Any thoughts on this would be appreciated. Have a nice day :)

**Comment by patrikja** [comment]
I don't get that error. Which version of pandoc are you using?
I have pandoc 1.13.2.1
I get another error instead;-) but the pdf is still produced.

! Undefined control sequence.
<argument> \Proportion

**Comment by MaximilianAlgehed** [comment]
Hi,

I am running version 1.16.0.2.

I fear my cabal-foo is not good enough to get version 1.13.2.1 running at the same time. I installed the version but I'm worried the pandoc binary is still on version 1.15.1.1 (which I presume is the version of the binary from version 1.16.0.2 of the library).

**Comment by MaximilianAlgehed** [comment]
Okay, so I got it working! The solution was to clone pandoc from git, build it and replace the old binary in /usr/bin/.
