### ISSUE TITLE
Make says there's nothing to do if modified included file

### ISSUE THREAD

**Issue by dheurlin** [DSLsofMath/DSLsofMath#31]
I have tried moving the exercises of week 1 to a separate file E1.lhs , which is then included in W01.lhs.
But when I modify E1.lhs and run make, it says there's nothing to do. In order for it to build, I have to do a dummy save in the including file.

**Comment by patrikja** [comment]
Solved by updating the Makefile: see b87c6a61b9805305641eea4f72e39250887ee7b0
