### ISSUE TITLE
Set up Fire instance for the Assignments

### ISSUE THREAD

**Issue by patrikja** [DSLsofMath/DSLsofMath#34]
Please set up a fire instance by 2018-01-02 and link to it from the course homepage.

**Comment by patrikja** [comment]
Is there a Fire instance up now?

**Comment by dschoepe** [comment]
I haven't heard back yet from the Fire people, they promised to set it up last week. I sent them a reminder and will add the URL as soon as it's up.

**Comment by dschoepe** [comment]
Alright, Fire instance is up now (though I referenced the wrong issue in the commit :)).
