### ISSUE TITLE
Cannot extract tarball (gzip: stdin: not in gzip format)

### ISSUE THREAD

**Issue by SimonAlling** [DSLsofMath/DSLsofMath#51]
> To do this, first make sure you have installed [stack](https://docs.haskellstack.org/en/stable/README/). Next, download [this tarball](https://github.com/DSLsofMath/DSLsofMath/blob/master/L/DSLsofMath-0.1.9.1.tar.gz) and extract it in a desired location (on Linux and Mac, you can do this by running `tar -zxf DSLsofMath-x.x.x.x.tar.gz` in the terminal.

    $ stack --version
    Version 1.7.1 x86_64
    (...)
    $ curl -O https://github.com/DSLsofMath/DSLsofMath/blob/master/L/DSLsofMath-0.1.9.1.tar.gz
    $ tar -zxf DSLsofMath-0.1.9.1.tar.gz 
    
    gzip: stdin: not in gzip format
    tar: Child returned status 1
    tar: Error is not recoverable: exiting now
    $ tar --version
    tar (GNU tar) 1.30
    (...)

I'm on NixOS 18.09.

@dheurlin and @hallavad say it works for them.

**Comment by Abhiroop** [comment]
@SimonAlling Could you try the following curl url instead with an additional -L option

`curl -OL https://github.com/DSLsofMath/DSLsofMath/raw/master/L/DSLsofMath-0.1.9.1.tar.gz`

And followed by that execute `tar -zxf DSLsofMath-0.1.9.1.tar.gz`

**Comment by SimonAlling** [comment]
That worked. Thank you!

By the way, even with the `raw` URL, `-L` seems to be necessary. I also tried downloading the file through GitHub's GUI (didn't occur to me when I created the issue), which worked without any problems. I suggest changing the link to `raw` instead of `blob` and adding something like "(in a CLI, use `curl` with the `-L` flag)".

**Comment by Abhiroop** [comment]
Updated the `README` with the CLI information. Closing this issue.

**Comment by ShreyasAmbre** [comment]
I m trying to extract the file given below 
apache-cassandra-4.0.0-bin.tar.gz

using below command :- 
tar -zxf apache-cassandra-4.0.0-bin.tar.gz

also tried this :- tar xzvf apache-cassandra-4.0.0-bin.tar.gz

download this file using below command :- curl -OL http://apache.mirror.digitalpacific.com.au/cassandra/4.0.0/apache-cassandra-4.0.0-bin.tar.gz
