### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by Kyuuhachi** [DSLsofMath/DSLsofMath#52]
In the [2017-08 exam](https://github.com/DSLsofMath/DSLsofMath/blob/2ac2b7d594382e9ceb87cb82cc1bd55bf6765199/Exam/2017-08/Exam-2017-08.lhs#L126), "give" is misspelled as "gice".

**Comment by patrikja** [comment]
Thanks. Fixed by commit 8f0b9bdd0e329601315ce3a94c8b19d3bb679941
