### ISSUE TITLE
Certain exercises relies on non existant import

### ISSUE THREAD

**Issue by The1Penguin** [DSLsofMath/DSLsofMath#73]
For example, https://github.com/DSLsofMath/DSLsofMath/blob/c4c963dcad1b83b4247703a309e1d0a614a3993c/L/02/ExerciseSolutions/E2_17_DeMorgan.lhs#L11
Which doesn't exist after building the project

**Comment by patrikja** [comment]
Thanks for the report. When the solution was added there was such a file in the repo and (thanks to git) it is still there: https://github.com/DSLsofMath/DSLsofMath/blob/cbf0b1c112dbd4015f3e834233307fa29ba00358/L/02/AbstractFOL.lhs
Using that should be a quick fix.
On the other hand, what was then in AbstractFOL.lhs is now in PropositionalLogic.lhs, with slightly different definitions. So ideally the exercise solution should be updated to use the new definitions. 
In either case, a pull request with a proposed solution would be appreciated.

**Comment by patrikja** [comment]
Now fixed with ce764c9
