### ISSUE TITLE
How to strip .lhs files to .hs files

### ISSUE THREAD

**Issue by Enayaaa** [DSLsofMath/DSLsofMath#76]
According to this post on  stackoverflow: https://stackoverflow.com/a/60122138
The program `unlit` which can be found in the lib folder of stack installation can do exactly this.
I found the program at `~/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.7/lib/ghc-8.10.7/bin/` on my machine.
You could use the following command to strip away text and comments from a .lhs file and keep the haskell code:
```~/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.7/lib/ghc-8.10.7/bin/unlit -n -c literate_haskell_file.lhs haskell_file.hs```

maybe we could copy over the unlit program into this repo?

**Comment by patrikja** [comment]
I have now used unlit to strip the LaTeX from all the Chapters and checked in the resulting "pure Haskell" files into the repo.
They all "work" in the sense of type check, but I have not had time to test them.
