### ISSUE TITLE
Visual issue with `@` symbol

### ISSUE THREAD

**Issue by Enayaaa** [DSLsofMath/DSLsofMath#85]
I do not have a suggestion how to solve this issue but looking at this rendering it doesn't look the best.
![image](https://user-images.githubusercontent.com/50826990/154081251-c43168e0-bf73-4e4b-82b8-f7650a5026df.png)
This specific one is from page 155 in the book snapshot.

**Comment by patrikja** [comment]
Thanks - now fixed in bafee8d
![Screenshot from 2022-02-17 10-00-03](https://user-images.githubusercontent.com/662883/154441499-3ce9b08f-1b0a-4954-b5ef-b299ddcb437d.png)
