### ISSUE TITLE
Small code readability suggestion

### ISSUE THREAD

**Issue by adelhult** [DSLsofMath/DSLsofMath#88]
**(Chapter 7, Linear algebra)**

It's a really nitpicky and arbitrary suggestion since it only comes down to style. But, I personally think that it might improve readability (just a tiny bit) if the order of the type parameters of the `Vector` type were flipped.

Current code:

```hs
newtype Vector s g = V (g -> s) deriving ...
```

Suggested change:
```hs
newtype Vector g s = V (g -> s) deriving ...
```
This would put them in the same order as the underlying (g -> s) type and as a bonus be a bit similar to how vector types are commonly named in other languages/libraries. `Vector2`, `Vector3`, etc...

**Comment by nicolabotta** [comment]
Hi Eli,

I might be wrong, of course, but I'm not sure that current choice is
just a matter of style.

If the first argument to |Vector| is |s|, then we can argue that, if |s|
is a field, then |Vector s| is a (finite) functor and a (finite) monad:

> class FinFunc f where
>   func    ::  (Finite g, Finite g') => (g -> g') -> f g -> f g'

> class FinMon f where
>   embed   ::  Finite g => g -> f g
>   bind    ::  Finite g => f g -> (g -> f g') -> f g'

> instance Field s => FinFunc (Vector s) where
>   func   =  funcFinFunc

> instance Field s => FinMon  (Vector s) where
>   embed  =  embedFinM
>   bind   =  bindFinM

> funcFinFunc :: (Field s, Finite g, Finite g') => (g -> g') -> Vector s g -> Vector s g'
> funcFinFunc = mulMV . invImage

> embedFinM :: (Eq g, Ring s) => g -> Vector s g
> embedFinM = e

> bindFinM :: (Field s, Finite g) => Vector s g -> (g -> Vector s g') -> Vector s g'
> bindFinM v m  = mulMV (transpose m) v   

> invImage :: (Field s, Eq g') => (g -> g') -> g' -> Vector s g
> invImage f = \ g' -> V (is g' . f)  

Thus, we can interpret linear transformations as monadic operations.

The problem with swapping arguments is that linear transformations are
not generic transformations between vector spaces but transformations
between vector spaces on the same field. Their type is

  Vector s g -> Vector s g'

The functor here is |Vector s| and the correspondent |map| takes indeed
as argument polymorphic functions |a -> b|, apart from the finiteness
constraint.

If we swap the arguments of |Vector|, we cannot any longer express the
functoriality of |Vector g| in terms of linear transformations.

Anyway, just my two cents, I'm not an expert on either linear algebra or
type theory.

But I think that you have raised an interesting question that we should
try to fully understand!

Ciao,
Nicola

**Comment by adelhult** [comment]
I see, seems like a super reasonable explanation, thank you for clarifying @nicolabotta!

I’ve never implemented a monad/functor instance by myself, so I’ve not really considered the importance of the order of the parameters in the type constructor when doing things like `m a` before. But this really helped me understand, so thanks!
