### ISSUE TITLE
Unsure if specification is correct?

### ISSUE THREAD

**Issue by Enayaaa** [DSLsofMath/DSLsofMath#89]
![image](https://user-images.githubusercontent.com/50826990/156428257-392575c1-26fd-4189-a1ba-32763caa1fa3.png)
The following specification on page 168 in the snapshot is a little confusing to me.
Is it ment that `eval` has type `PS REAL -> (REAL -> REAL)`? Then it doesn't make sense for me if the `eval` function in RHS is same as LHS. if the type is as above I would expect the RHS to be `exp . (eval as)`

**Comment by patrikja** [comment]
It is actually type correct as written, because the function instance of Transcedental (which implements exp f = exp . f) but I agree it is confusing. In commit 0b2ac31 I have clarified it by expanding the function instance part in the specification and the calculation./P
