### ISSUE TITLE
What is ment by group structure?

### ISSUE THREAD

**Issue by Enayaaa** [DSLsofMath/DSLsofMath#90]
I was a little confused by the text on the second law for vector space.
![image](https://user-images.githubusercontent.com/50826990/156635377-f0d2ff63-0f23-4f57-9683-2d2a355ec734.png)
I do not understand what is ment when it is said `from the additive group structure of s to the group structure of v`.

What group structure of `v` are we talking about? The additive group structure? Because in that case it would make sense to me when looking at the different rules under this law.

**Comment by nicolabotta** [comment]
Hi Enayatullah,

vector spaces have been introduced as a set of scalars with a field
structure, a set of vectors with an additive group structure and the
scalar-vector multiplication "scale":  

> class (Field s, AddGroup v) => VectorSpace v s where
>   (*^) :: s -> v -> v

Thus there is only one group structure on the vectors, the additive.

Ciao,
Nicola
